# This modul is generated by main.py
# This modul is crawling values from xlsx files

import csv
import pandas as pd

def crawl_files(lists, type_of_crawl)-> list:
    """ 
    Сканирование данных 
    """
    flat_lists = []
    for my_csv_file in lists:
        if type_of_crawl == 'horizontally':
            with open(my_csv_file, 'r', encoding = 'utf-8') as f:
                reader = csv.reader(f)
                my_list = list(reader)
                # перевод всех данных csv в строку
                flat_list = [str(item) for sublist in my_list for item in sublist]
                flat_lists.append(flat_list)
        elif type_of_crawl == 'vertically':
            df = pd.read_csv(my_csv_file)
            # генератор прогоняет по каждому столбцу pandas
            flat_list = [item for column in df.columns.tolist() for item  in df[column].tolist() if str(item)!='nan']
            flat_lists.append(flat_list)
    return flat_lists