# This modul is generated by main.py


import pandas as pd


# словарь с атрибутами для отношения Act_of_transfer
print('Формирование блока информации: АКТ ПРИЕМА-ПЕРЕДАЧ...')

Act_of_transfer = {
    # Атрибут 1. Договор на захоронение (внешний ключ)
    'contract_id': name_contracts(checking_files, 'name_of_contract'),

    # Атрибут 2. Дата составления договора на захоронение (внешний ключ)
    'contract_date_id': name_contracts(checking_files, 'date'),

    # Атрибут 3. Номер акта приема-передач
    'number_of_act': input_value('Номер акта приема передач', 'String_Value'),

    # Атрибут 4. Дата составления акта приема-передач
    'date_of_act': input_value('Дата составления акта приема-передач', 'String_Value'),

    # Атрибут 5. Организация-собственник упаковок РАО (внешний ключ)
    'OKPO_organization': input_value('ОКПО организации', 'String_Value'),

    # Атрибут 6. Специализированная организация, через которую осуществлялась передача РАО (внешний ключ)
    'OKPO_special_organization': input_value('ОКПО специализированной организации', 'String_Value'),

    # Атрибут 7. Дата приема РАО на захоронение
    'date_of_brining': input_value('Дата приема РАО на захоронение', 'String_Value'),

    # Атрибут 8. Объем принятых РАО на захоронение
    'volume_of_raw': parsing_values('объем', 'брутто', checking_files, 'act_of_transfer'),
}

# словарь с атрибутами для отношения Certification
print('Формирование блока информации: СЕРТИФИКАТ СООТВЕТСТВИЯ...')

Certification = {
    # Атрибут 1. Первичный ключ сертификата соответствия на упаковку РАО
    'certification_id': None,

    # Атрибут 2. Номер сертификата
    'number_certification': get_certification_name(checking_files),

    # Атрибут 3. Начало действия сертификата
    'begining_cert': None,

    # Атрибут 4. Окончаение действия сертификата
    'ending_cert': None,
}

# словарь с атрибутами для отношения Passports_RAW
print('Формирование блока информации: Паспорт на упаковку РАО...')

Passports_RAW = {
    # Атрибут 1. Номер упаковки РАО (внутренний и внешний ключ РАО)
    'raw_package_id': None,

    # Атрибут 2. Номер паспорта на упаковку РАО
    'passport_number': get_name_of_passport(checking_files),

    # Атрибут 3. Дата составления паспорта на упаковку РАО
    'passport_date': get_date_of_passport(checking_files),

    # Атрибут 4. Ответственный за сдачу РАО
    'reception_man': None,

    # Атрибут 5. Ответственный за прием РАО
    'responce_man': None,
}

# словарь с атрибутами для отношения Raw_package

Raw_package = {
    # Атрибут 1. Идентификатор упаковки РАО
    'raw_package_id': None,

    # Атрибут 2. Контейнер (внешний ключ)
    'bag_id': None,

    # Атрибут 3. Договор на захоронение (внешний ключ)
    'contract_id': None,

    # Атрибут 4. Договор на временное хранение (внешний ключ, если имеется)
    'temp_contract_id': None,

    # Атрибут 5. Класс РАО (либо 3 или 4)
    'class_raw': None,

    # Атрибут 6. Заводской номер контейнера.
    'factory_number': id_bags(checking_files),

    # Атрибут 7. Масса упаковки РАО, кг
    'weight_brutto': None,

    # Атрибут 8. Масса отходов, кг
    'weight_netto': None,

    # Атрибут 9. Объем отходов брутто, куб. м (по документам)
    'volume_brutto': None,

    # Атрибут 10. Объем отходов нетто, куб. м (по документам)
    'volume_netto': None,

    # Атрибут 11. Наличие и вид матричного материала
    'matrix_material': None,

    # Атрибут 12. Наличие и вид инертного материала
    'inert_material': None,

    # Атрибут 13. Статус РАО
    'status_raw': None,

    # Атрибут 14. Дата передачи упаковки РАО на захоронение
    'date_brining': None,

    # Атрибут 15. Местоположение контейнера (103, 133, 10, 11, 12, 13)
    'coordinates': None,

    # Атрибут 16. ОКПО (Организация-собственник упаковки РАО)
    'org_property': None,

    # Атрибут 17. ОКПО (Организация-изготовитель упаковки РАО)
    'org_producer': None,

    # Атрибут 18. Код РАО
    'code_raw': None,

    # Атрибут 19. Общая активность в упаковке РАО, Бк
    'general_activity': None,

    # Атрибут 20. Дата формирования упаковки РАО
    'date_of_forming_bag': None,

    # Атрибут 21. Дата формирования контейнера
    'date_of_forming_container': None,

    # Атрибут 22. Сертификат-соответствия на контейнер
    'certification_id': None,
}

# словарь с атрибутами для отношения Rn_measure

Rn_measure = {
    # Атрибут 1. Первичный ключ измерения
    'rn_measure_id': None,

    # Атрибут 2. Идентификационный код упаковки РАО
    'raw_package_id': None,

    # Атрибут 3. Идентификационный код радионуклида (краткое наименование радионуклида)
    'radionucklid_id': None,

    # Атрибут 4. Удельная активность радионуклида, Бк/г
    'rn_udel_activity': None,

    # Атрибут 5. Дата измерения активности
    'date_meas_active': None,
}

writer = pd.ExcelWriter(path_of_incoming_folder + 'parse.xlsx', engine = 'xlsxwriter')

# отношение № 1 "Акт приема-передач"
act_of_transfer_dataframe = pd.DataFrame(Act_of_transfer)
act_of_transfer_dataframe.to_excel(writer, sheet_name = 'Act_of_transfer', index = False)

# отношение № 2 "Сертификат-соответствия на контейнер"
certification_dataframe = pd.DataFrame(Certification)
certification_dataframe.to_excel(writer, sheet_name = 'Certification', index = False)

# отношение № 3 "Паспорт на упаковку РАО"

passports_raw_dataframe = pd.DataFrame(Passports_RAW)
passports_raw_dataframe.to_excel(writer, sheet_name = 'Passports_RAW', index = False)

# # отношение № 4 "Содержимое упаковки РАО"
# raw_package_dataframe = pd.DataFrame(Raw_package)
# raw_package_dataframe.to_excel(writer, sheet_name = 'Raw_package', index = False)

# # отношение № 5 "Удельные активности в упаковке РАО"
# rn_measure_dataframe = pd.DataFrame(Rn_measure)

writer.save()