# This modul is generated by main.py

import os
import xlrd
import csv

def creating_csv_files(path_source: str) -> list:
    """
    Формирование списка файлов, предназначенных для форматирования
    Преобразование файлов с расширением .xlsx в .csv 
    Формирование списка файлов с расширением .csv для парсинга сведений
    """

    # формируем список файлов с расширением .xlsx
    directory_lists_of_incoming_files = os.listdir(path_source)
    print('Processing ' + str(len(directory_lists_of_incoming_files)) + ' files with the extensions .xlsx in directory: ' + path_source + '/')
    # формируем список путей к файлам с расширением .xlsx
    lists_of_incoming_files = [path_source + '/' + incoming_file for incoming_file in directory_lists_of_incoming_files]
    # указываем абсолютный путь к будущей директории с файлами с расширением .csv
    path_of_incoming_folder_csv = path_source + '_csv/'
    # создаем директорию, в которой будут складываться файлы с расширением .csv
    os.mkdir(path_of_incoming_folder_csv)

    try:
        for my_file in lists_of_incoming_files:
            wb = xlrd.open_workbook(my_file)
            sheet_names = wb.sheet_names()[0]
            sh = wb.sheet_by_name(sheet_names)

            csv_file = my_file.split('.')[0] + '.csv'
            csv_file = path_of_incoming_folder_csv + csv_file.split('/')[-1]

            your_csv_file = open(csv_file, 'w', encoding = 'utf-8')
            wr = csv.writer(your_csv_file, quoting = csv.QUOTE_ALL)

            for rownum in range(sh.nrows): 
                wr.writerow(sh.row_values(rownum))
            your_csv_file.close()

        csv_files = os.listdir(path_of_incoming_folder_csv)
        directory_lists = [path_of_incoming_folder_csv + i for i in csv_files]
        print('Processed ' + str(len(directory_lists)) + ' files with the extensions .csv in directory: ' + path_of_incoming_folder_csv)
        return directory_lists
    except:
        input('Processing of creating_csv_files is FAILED! Please, check function')


def remove_files_and_dir(path_source: str):
    """
    Функция для удаления
    файлов c расширением .csv
    и самой корневой папки
    """
    try:
        directory_lists_of_files = os.listdir(path_source + '_csv/')
        # удаление файлов с расширением .csv
        for file in directory_lists_of_files:
            os.remove(path_source + '_csv/' + file)
        # удаление пустой директории
        os.rmdir(path_source + '_csv/')
    except:
        None
